function y = preprocess(x)
%  预处理输入 x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 07-Sep-2024 12:39:16

Fs = 1; % 平均采样率

y = smoothdata(y,'gaussian','SmoothingFactor',0.4);

